return {
	"ThePrimeagen/refactoring.nvim",
	"nvim-lua/plenary.nvim",
	"kosayoda/nvim-lightbulb",
	"RishabhRD/popfix",
	"ray-x/guihua.lua",
	"goolord/alpha-nvim",
	"nvim-lualine/lualine.nvim",
	"mrjones2014/legendary.nvim",
	"voldikss/vim-floaterm",
	"skywind3000/asyncrun.vim",
	"Exafunction/codeium.vim",
	"jackMort/ChatGPT.nvim",
	"folke/which-key.nvim",
	"kevinhwang91/promise-async",
	"MunifTanjim/nui.nvim",
	"rcarriga/nvim-notify",
}
